using static UltrakULL.json.LanguageManager;

namespace UltrakULL;

public static class EnemyBios
{
	[NeedRework]
	public static string GetName(string originalName)
	{
		return originalName.ToUpper() switch
		{
			var n when n.Contains("RADIANT") && n.Contains("SWORDSMACHINE") => CurrentLanguage.enemyNames.enemyname_radiant_swordsmachine,
			var n when n.Contains("RADIANT") && n.Contains("CERBERUS") => CurrentLanguage.enemyNames.enemyname_radiant_cerberus,
			var n when n.Contains("RADIANT") && n.Contains("HIDEOUS MASS") => CurrentLanguage.enemyNames.enemyname_radiant_hideousMass,
			var n when n.Contains("RADIANT") => originalName,
			"SWORDSMACHINE" => CurrentLanguage.enemyNames.enemyname_swordsmachine,
			"SWORDSMACHINE DEFAULT" => CurrentLanguage.enemyNames.enemyname_swordsmachine,
			"SWORDSMACHINE \"AGONY\"" => CurrentLanguage.enemyNames.enemyname_boss_swordsmachineAgony,
			"SWORDSMACHINE \"TUNDRA\"" => CurrentLanguage.enemyNames.enemyname_boss_swordsmachineTundra,
			"INSURRECTIONIST \"ANGRY\"" => CurrentLanguage.enemyNames.enemyname_boss_insurrectionistAngry,
			"INSURRECTIONIST \"RUDE\"" => CurrentLanguage.enemyNames.enemyname_boss_insurrectionistRude,
			"INSURRECTIONIST DEFAULT" or "INSURRECTIONIST" => CurrentLanguage.enemyNames.enemyname_insurrectionist,
			"SISYPHEAN INSURRECTIONIST" => CurrentLanguage.enemyNames.enemyname_boss_insurrectionist,
			"FILTH" => CurrentLanguage.enemyNames.enemyname_filth,
			"STRAY" => CurrentLanguage.enemyNames.enemyname_stray,
			"SCHISM" => CurrentLanguage.enemyNames.enemyname_schism,
			"SOLDIER" => CurrentLanguage.enemyNames.enemyname_soldier,
			"MINOS" or "THE CORPSE OF KING MINOS" => CurrentLanguage.enemyNames.enemyname_boss_corpseOfKingMinos,
			"STALKER" => CurrentLanguage.enemyNames.enemyname_stalker,
			"VERY CANCEROUS RODENT" => CurrentLanguage.enemyNames.enemyname_boss_veryCancerousRodent,
			"CANCEROUS RODENT" => CurrentLanguage.enemyNames.enemyname_boss_cancerousRodent,
			"FERRYMAN" => CurrentLanguage.enemyNames.enemyname_ferryman,
			"FERRYMAN \"RUDRAKSHA\"" => CurrentLanguage.enemyNames.enemyname_boss_ferrymanRudraksha,
			"FERRYMAN \"AGONIS\"" => CurrentLanguage.enemyNames.enemyname_boss_ferrymanAgonis,
			"DRONE" => CurrentLanguage.enemyNames.enemyname_drone,
			"STREETCLEANER" => CurrentLanguage.enemyNames.enemyname_streetCleaner,
			"V2 (2ND)" => CurrentLanguage.enemyNames.enemyname_v2Second,
			"V2SECOND" or "V2" => CurrentLanguage.enemyNames.enemyname_v2,
			"TURRET" or "SENTRY" => CurrentLanguage.enemyNames.enemyname_sentry,
			"GUTTERMAN" => CurrentLanguage.enemyNames.enemyname_gutterman,
			"GUTTERTANK" => CurrentLanguage.enemyNames.enemyname_guttertank,
			"MINDFLAYER" => CurrentLanguage.enemyNames.enemyname_mindFlayer,
			"CENTAUR" => CurrentLanguage.enemyNames.enemyname_boss_earthmover,
			"1000-THR DEFENCE SYSTEM" => CurrentLanguage.enemyNames.enemyname_boss_earthmoverDefence,
			"EARTHMOVER" => CurrentLanguage.enemyNames.enemyname_earthmover,
			"MALICIOUSFACE" or "MALICIOUS FACE" => CurrentLanguage.enemyNames.enemyname_malFace,
			"MYSTERIOUS DRUID KNIGHT (& OWL)" => CurrentLanguage.enemyNames.enemyname_boss_mandalore,
			"IDOL" => CurrentLanguage.enemyNames.enemyname_idol,
			"LEVIATHAN" => CurrentLanguage.enemyNames.enemyname_leviathan,
			"CERBERUS, GUARDIAN OF HELL" => CurrentLanguage.enemyNames.enemyname_boss_cerberus,
			"STATUE" or "CERBERUS" => CurrentLanguage.enemyNames.enemyname_cerberus,
			"HIDEOUS MASS" or "HIDEOUSMASS" => CurrentLanguage.enemyNames.enemyname_hideousMass,
			"MANNEQUIN" => CurrentLanguage.enemyNames.enemyname_mannequin,
			"MINOTAUR" or "<S>MINOTAUR" or "<s>MINOTAUR" => "<s>" + CurrentLanguage.enemyNames.enemyname_minotaur + "</s>",
			"GABRIEL, JUDGE OF HELL" => CurrentLanguage.enemyNames.enemyname_boss_gabriel,
			"GABRIEL, APOSTATE OF HATE" or "GABRIEL, THE APOSTATE OF HATE" => CurrentLanguage.enemyNames.enemyname_boss_gabrielSecond,
			"VIRTUE" => CurrentLanguage.enemyNames.enemyname_virtue,
			"SOMETHING WICKED" => CurrentLanguage.enemyNames.enemyname_somethingWicked,
			"???" => CurrentLanguage.enemyNames.enemyname_puppet,
			"FLESH PRISON" => CurrentLanguage.enemyNames.enemyname_boss_fleshPrison,
			"MINOSPRIME" or "MINOS PRIME" => CurrentLanguage.enemyNames.enemyname_boss_minosPrime,
			"FLESH PANOPTICON" => CurrentLanguage.enemyNames.enemyname_boss_fleshPanopticon,
			"SISYPHUSPRIME" or "SISYPHUS PRIME" => CurrentLanguage.enemyNames.enemyname_boss_sisyphusPrime,
			"BIG JOHNINATOR" or "BIGJOHNATOR" => CurrentLanguage.enemyNames.enemyname_boss_bigJohninator,
			"1000-THR \"EARTHMOVER\"" => CurrentLanguage.enemyNames.enemyname_boss_earthmover,
			"1000-THR DEFENSE SYSTEM" => CurrentLanguage.enemyNames.enemyname_boss_earthmoverDefence,
			"EARTHMOVER MORTAR" => CurrentLanguage.enemyNames.enemyname_earthmoverMortar,
			"EARTHMOVER ROCKET LAUNCHER" => CurrentLanguage.enemyNames.enemyname_earthmoverRocketLauncher,
			"EARTHMOVER TOWER" => CurrentLanguage.enemyNames.enemyname_earthmoverTower,
			"GERYON" => CurrentLanguage.enemyNames.enemyname_geryon,
			"PROVIDENCE" => CurrentLanguage.enemyNames.enemyname_boss_providence,
			"DEATHCATCHER" => CurrentLanguage.enemyNames.enemyname_deathcatcher,
			"MIRROR REAPER" => CurrentLanguage.enemyNames.enemyname_boss_mirrorReaper,
			"POWER" => CurrentLanguage.enemyNames.enemyname_power,
			"POWER MANADEL" or "POWER \"MANADEL\"" => CurrentLanguage.enemyNames.enemyname_boss_powerManadel,
			"POWER \"LEHAHIAH\"" or "POWER LEHAHIAH" => CurrentLanguage.enemyNames.enemyname_boss_powerLehahiah,
			"POWER CHAUAKIAH" or "POWER \"CHAUAKIAH\"" => CurrentLanguage.enemyNames.enemyname_boss_powerChauakiah,
			"GERYON, WATCHER OF THE SKIES" => CurrentLanguage.enemyNames.enemyname_boss_geryon,
			_ => originalName,
		};
	}

	public static string GetType(string originaltype)
	{
		return originaltype.ToUpper() switch
		{
			"LESSER HUSK" => CurrentLanguage.enemyNames.enemyname_type_lesserHusk,
			"GREATER HUSK" => CurrentLanguage.enemyNames.enemyname_type_greaterHusk,
			"SUPREME HUSK" => CurrentLanguage.enemyNames.enemyname_type_supremeHusk,
			"LESSER DEMON" => CurrentLanguage.enemyNames.enemyname_type_lesserDemon,
			"GREATER DEMON" => CurrentLanguage.enemyNames.enemyname_type_greaterDemon,
			"SUPREME DEMON" => CurrentLanguage.enemyNames.enemyname_type_supremeDemon,
			"LESSER MACHINE" => CurrentLanguage.enemyNames.enemyname_type_lesserMachine,
			"GREATER MACHINE" => CurrentLanguage.enemyNames.enemyname_type_greaterMachine,
			"SUPREME MACHINE" => CurrentLanguage.enemyNames.enemyname_type_supremeMachine,
			"LESSER ANGEL" => CurrentLanguage.enemyNames.enemyname_type_lesserAngel,
			"GREATER ANGEL" => CurrentLanguage.enemyNames.enemyname_type_greaterAngel,
			"SUPREME ANGEL" => CurrentLanguage.enemyNames.enemyname_type_supremeAngel,
			"???" => "???",
			"PRIME SOUL" => CurrentLanguage.enemyNames.enemyname_type_primeSoul,
			_ => originaltype,
		};
	}

	public static string GetDescription(string originalenemy, string originalDescription = null)
	{
		return originalenemy.ToUpper() switch
		{
			"FILTH" => CurrentLanguage.enemyBios.enemyBios_filth_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_filth_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_filth_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_filth_4,
			"STRAY" => CurrentLanguage.enemyBios.enemyBios_stray_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_stray_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_stray_3,
			"SCHISM" => CurrentLanguage.enemyBios.enemyBios_schism_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_schism_2,
			"SOLDIER" => CurrentLanguage.enemyBios.enemyBios_soldier_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_soldier_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_soldier_3,
			"IDOL" => CurrentLanguage.enemyBios.enemyBios_idol_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_idol_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_idol_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_idol_4,
			"THE CORPSE OF KING MINOS" => CurrentLanguage.enemyBios.enemyBios_corpseOfKingMinos_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_corpseOfKingMinos_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_corpseOfKingMinos_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_corpseOfKingMinos_4,
			"STALKER" => CurrentLanguage.enemyBios.enemyBios_stalker_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_stalker_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_stalker_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_stalker_4 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_stalker_5,
			"INSURRECTIONIST" => CurrentLanguage.enemyBios.enemyBios_insurrectionist_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_insurrectionist_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_insurrectionist_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_insurrectionist_4 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_insurrectionist_5 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_insurrectionist_6,
			"FERRYMAN" => CurrentLanguage.enemyBios.enemyBios_ferryman_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_ferryman_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_ferryman_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_ferryman_4 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_ferryman_5 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_ferryman_6,
			"SWORDSMACHINE" => CurrentLanguage.enemyBios.enemyBios_swordsmachine_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_swordsmachine_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_swordsmachine_3,
			"DRONE" => CurrentLanguage.enemyBios.enemyBios_drone_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_drone_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_drone_3,
			"STREETCLEANER" => CurrentLanguage.enemyBios.enemyBios_streetcleaner_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_streetcleaner_2,
			"V2" => CurrentLanguage.enemyBios.enemyBios_v2_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_v2_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_v2_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_v2_4 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_v2_5,
			"MINDFLAYER" => CurrentLanguage.enemyBios.enemyBios_mindflayer_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_mindflayer_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_mindflayer_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_mindflayer_4 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_mindflayer_5,
			"V2 (2ND)" => CurrentLanguage.enemyBios.enemyBios_v2Second_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_v2Second_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_v2Second_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_v2Second_4,
			"SENTRY" => CurrentLanguage.enemyBios.enemyBios_sentry_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_sentry_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_sentry_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_sentry_4,
			"GUTTERMAN" => CurrentLanguage.enemyBios.enemyBios_gutterman_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_gutterman_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_gutterman_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_gutterman_4,
			"GUTTERTANK" => CurrentLanguage.enemyBios.enemyBios_guttertank_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_guttertank_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_guttertank_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_guttertank_4 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_guttertank_5 + " " + CurrentLanguage.enemyBios.enemyBios_guttertank_6 + " " + CurrentLanguage.enemyBios.enemyBios_guttertank_7,
			"EARTHMOVER" => CurrentLanguage.enemyBios.enemyBios_earthmover_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_earthmover_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_earthmover_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_earthmover_4 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_earthmover_5 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_earthmover_6,
			"MALICIOUS FACE" => CurrentLanguage.enemyBios.enemyBios_maliciousFace_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_maliciousFace_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_maliciousFace_3,
			"CERBERUS" => CurrentLanguage.enemyBios.enemyBios_cerberus_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_cerberus_2,
			"HIDEOUS MASS" => CurrentLanguage.enemyBios.enemyBios_hideousMass_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_hideousMass_2,
			"LEVIATHAN" => CurrentLanguage.enemyBios.enemyBios_leviathan_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_leviathan_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_leviathan_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_leviathan_4,
			"MANNEQUIN" => CurrentLanguage.enemyBios.enemyBios_mannequin_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_mannequin_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_mannequin_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_mannequin_4 + "\n\n" + CurrentLanguage.enemyBios.enemyBios_mannequin_5,
			"MINOTAUR" or "<S>MINOTAUR" or "<s>MINOTAUR" => CurrentLanguage.enemyBios.enemyBios_minotaur_1 + "\n\n\n...\n\n\n...\n\n\n...\n\n\n<s><color=red>" + CurrentLanguage.enemyBios.enemyBios_minotaur_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_minotaur_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_minotaur_4 + "</color></s>",
			"GABRIEL, JUDGE OF HELL" => CurrentLanguage.enemyBios.enemyBios_gabriel_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_gabriel_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_gabriel_3,
			"GABRIEL, APOSTATE OF HATE" => CurrentLanguage.enemyBios.enemyBios_gabrielSecond_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_gabrielSecond_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_gabrielSecond_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_gabrielSecond_4,
			"VIRTUE" => CurrentLanguage.enemyBios.enemyBios_virtue_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_virtue_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_virtue_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_virtue_4 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_virtue_5,
			"SOMETHING WICKED" => CurrentLanguage.enemyBios.enemyBios_somethingWicked_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_somethingWicked_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_somethingWicked_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_somethingWicked_4,
			"FLESH PRISON" => CurrentLanguage.enemyBios.enemyBios_fleshPrison_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_fleshPrison_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_fleshPrison_3,
			"MINOS PRIME" => CurrentLanguage.enemyBios.enemyBios_minosPrime_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_minosPrime_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_minosPrime_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_minosPrime_4 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_minosPrime_5 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_minosPrime_6 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_minosPrime_7 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_minosPrime_8,
			"FLESH PANOPTICON" => CurrentLanguage.enemyBios.enemyBios_fleshPanopticon_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_fleshPanopticon_2,
			"SISYPHUS PRIME" => CurrentLanguage.enemyBios.enemyBios_sisyphusPrime_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_sisyphusPrime_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_sisyphusPrime_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_sisyphusPrime_4 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_sisyphusPrime_5 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_sisyphusPrime_6 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_sisyphusPrime_7 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_sisyphusPrime_8,
			"PROVIDENCE" => CurrentLanguage.enemyBios.enemyBios_providence_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_providence_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_providence_3,
			"POWER" => CurrentLanguage.enemyBios.enemyBios_power_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_power_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_power_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_power_4,
			"GERYON" => CurrentLanguage.enemyBios.enemyBios_geryon_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_geryon_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_geryon_3 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_geryon_4,
			"MIRROR REAPER" => CurrentLanguage.enemyBios.enemyBios_mirrorReaper_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_mirrorReaper_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_mirrorReaper_3,
			"DEATHCATCHER" => CurrentLanguage.enemyBios.enemyBios_deathcatcher_1 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_deathcatcher_2 + "\n\n\n" + CurrentLanguage.enemyBios.enemyBios_deathcatcher_3,
			_ => originalDescription ?? originalenemy,
		};
	}

	public static string GetStrategy(string originalenemy, string originalStrategy = null)
	{
		return originalenemy.ToUpper() switch
		{
			"FILTH" => "- " + CurrentLanguage.enemyBios.enemyBios_filth_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_filth_strategy2,
			"STRAY" => "- " + CurrentLanguage.enemyBios.enemyBios_stray_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_stray_strategy2,
			"SCHISM" => "- " + CurrentLanguage.enemyBios.enemyBios_schism_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_schism_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_schism_strategy3,
			"SOLDIER" => "- " + CurrentLanguage.enemyBios.enemyBios_soldier_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_soldier_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_soldier_strategy3,
			"FERRYMAN" => "- " + CurrentLanguage.enemyBios.enemyBios_ferryman_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_ferryman_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_ferryman_strategy3 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_ferryman_strategy4,
			"SENTRY" => "- " + CurrentLanguage.enemyBios.enemyBios_sentry_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_sentry_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_sentry_strategy3 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_sentry_strategy4,
			"IDOL" => "- " + CurrentLanguage.enemyBios.enemyBios_idol_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_idol_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_idol_strategy3 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_idol_strategy4,
			"THE CORPSE OF KING MINOS" => "- " + CurrentLanguage.enemyBios.enemyBios_corpseOfKingMinos_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_corpseOfKingMinos_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_corpseOfKingMinos_strategy3,
			"LEVIATHAN" => "- " + CurrentLanguage.enemyBios.enemyBios_leviathan_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_leviathan_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_leviathan_strategy3,
			"STALKER" => "- " + CurrentLanguage.enemyBios.enemyBios_stalker_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_stalker_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_stalker_strategy3 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_stalker_strategy4,
			"INSURRECTIONIST" => "- " + CurrentLanguage.enemyBios.enemyBios_insurrectionist_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_insurrectionist_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_insurrectionist_strategy3 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_insurrectionist_strategy4,
			"SWORDSMACHINE" => "- " + CurrentLanguage.enemyBios.enemyBios_swordsmachine_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_swordsmachine_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_swordsmachine_strategy3,
			"DRONE" => "- " + CurrentLanguage.enemyBios.enemyBios_drone_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_drone_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_drone_strategy3 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_drone_strategy4,
			"STREETCLEANER" => "- " + CurrentLanguage.enemyBios.enemyBios_streetcleaner_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_streetcleaner_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_streetcleaner_strategy3,
			"V2" => "- " + CurrentLanguage.enemyBios.enemyBios_v2_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_v2_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_v2_strategy3 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_v2_strategy4,
			"MINDFLAYER" => "- " + CurrentLanguage.enemyBios.enemyBios_mindflayer_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_mindflayer_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_mindflayer_strategy3,
			"V2 (2ND)" => "- " + CurrentLanguage.enemyBios.enemyBios_v2Second_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_v2Second_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_v2Second_strategy3,
			"GUTTERMAN" => "- " + CurrentLanguage.enemyBios.enemyBios_gutterman_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_gutterman_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_gutterman_strategy3 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_gutterman_strategy4,
			"GUTTERTANK" => "- " + CurrentLanguage.enemyBios.enemyBios_guttertank_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_guttertank_strategy2,
			"EARTHMOVER" => "- " + CurrentLanguage.enemyBios.enemyBios_earthmover_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_earthmover_strategy2,
			"MALICIOUS FACE" => "- " + CurrentLanguage.enemyBios.enemyBios_maliciousFace_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_maliciousFace_strategy2,
			"CERBERUS" => "- " + CurrentLanguage.enemyBios.enemyBios_cerberus_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_cerberus_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_cerberus_strategy3,
			"HIDEOUS MASS" => "- " + CurrentLanguage.enemyBios.enemyBios_hideousMass_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_hideousMass_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_hideousMass_strategy3 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_hideousMass_strategy4,
			"MANNEQUIN" => "- " + CurrentLanguage.enemyBios.enemyBios_mannequin_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_mannequin_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_mannequin_strategy3,
			"MINOTAUR" or "<S>MINOTAUR" or "<s>MINOTAUR" => "- " + CurrentLanguage.enemyBios.enemyBios_minotaur_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_minotaur_strategy2,
			"GABRIEL, JUDGE OF HELL" => "- " + CurrentLanguage.enemyBios.enemyBios_gabriel_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_gabriel_strategy2,
			"GABRIEL, APOSTATE OF HATE" => "- " + CurrentLanguage.enemyBios.enemyBios_gabrielSecond_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_gabrielSecond_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_gabrielSecond_strategy3,
			"VIRTUE" => "- " + CurrentLanguage.enemyBios.enemyBios_virtue_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_virtue_strategy2,
			"SOMETHING WICKED" => "- " + CurrentLanguage.enemyBios.enemyBios_somethingWicked_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_somethingWicked_strategy2,
			"FLESH PRISON" => "- " + CurrentLanguage.enemyBios.enemyBios_fleshPrison_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_fleshPrison_strategy2,
			"MINOS PRIME" => "- " + CurrentLanguage.enemyBios.enemyBios_minosPrime_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_minosPrime_strategy2,
			"FLESH PANOPTICON" => "- " + CurrentLanguage.enemyBios.enemyBios_fleshPanopticon_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_fleshPanopticon_strategy2,
			"SISYPHUS PRIME" => "- " + CurrentLanguage.enemyBios.enemyBios_sisyphusPrime_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_sisyphusPrime_strategy2,
			"PROVIDENCE" => "- " + CurrentLanguage.enemyBios.enemyBios_providence_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_providence_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_providence_strategy3 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_providence_strategy4,
			"POWER" => "- " + CurrentLanguage.enemyBios.enemyBios_power_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_power_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_power_strategy3 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_power_strategy4,
			"GERYON" => "- " + CurrentLanguage.enemyBios.enemyBios_geryon_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_geryon_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_geryon_strategy3,
			"MIRROR REAPER" => "- " + CurrentLanguage.enemyBios.enemyBios_mirrorReaper_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_mirrorReaper_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_mirrorReaper_strategy3 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_mirrorReaper_strategy4,
			"DEATHCATCHER" => "- " + CurrentLanguage.enemyBios.enemyBios_deathcatcher_strategy1 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_deathcatcher_strategy2 + "\n\n\n- " + CurrentLanguage.enemyBios.enemyBios_deathcatcher_strategy3,
			_ => originalStrategy ?? originalenemy,
		};
	}
}
